### PR TITLE
Update create-undefs.pl

### PR DESCRIPTION
**Pull request by dukess**
JSON generation

### CODE REVIEW

**Comment by fredlcore** [comment]
That means there will be a JavaScript and a JSON output generation, is that correct? If so, where is the difference? Just for my understanding, I'll merge this anyway.

**Comment by fredlcore** [comment]
Hmm, strange, I can't merge this pull request?

**Comment by dukess** [comment]
> That means there will be a JavaScript and a JSON output generation, is that correct? If so, where is the difference? Just for my understanding, I'll merge this anyway.

You right. Difference in format. In "js" files, values are assigned to array elements. In other words, these files are tightly bound to the JavaScript syntax.

> Hmm, strange, I can't merge this pull request?

This pull request to my repository.
Moment. I make pull request to main repo.

**Comment by fredlcore** [comment]
Ah, ok, sorry ;) - take your time...

**Pull request closed without merging**
